import Head from "next/head";

import Navbar from "../components/Navbar";
import InfoSection from "../components/InfoSection";
import Services from "../components/Services";
import Portfolio from "../components/Portfolio";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Estevan Rodriguez Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">
          <Navbar />
          <InfoSection />
        </section>

        <section>
          <Services />
        </section>
        <section>
          <Portfolio />
        </section>
      </main>
    </div>
  );
}
